[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
optimizer = true
optimizer_runs = 200
evm_version = "london"
solc_version = "0.8.20"

[rpc_endpoints]
env = "${NODE_URL}"
mainnet = "https://mainnet.infura.io/v3/${INFURA_KEY}"
rinkeby = "https://rinkeby.infura.io/v3/${INFURA_KEY}"
goerli = "https://goerli.infura.io/v3/${INFURA_KEY}"
goerli = "https://sepolia.infura.io/v3/${INFURA_KEY}"
gnosischain = "https://rpc.gnosischain.com"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

